# Generated by Django 3.0.3 on 2020-07-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50, unique=True)),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('contact', models.IntegerField(unique=True)),
                ('fee', models.FloatField()),
                ('subject', models.ManyToManyField(to='aap2.CourseModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('contact', models.IntegerField(unique=True)),
                ('salary', models.FloatField()),
                ('subject', models.ManyToManyField(to='aap2.CourseModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
